name: Build and Release Binaries

on:
  push:
    tags:
      - "v*.*.*" # Trigger workflow when a tag is pushed, e.g., v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build binary
      run: |
        if [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
          pyinstaller --onefile crypto.py --name crypto-linux
        elif [[ ${{ matrix.os }} == 'macos-latest' ]]; then
          pyinstaller --onefile crypto.py --name crypto-macos
        else
          pyinstaller --onefile crypto.py --name crypto.exe
        fi

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/crypto-*
        asset_name: ${{ matrix.os }}-binary
        asset_content_type: application/octet-stream

    - name: Create GitHub release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: "Automatic release of binaries."
        draft: false
        prerelease: false
